### ISSUE TITLE
Github Action Failures for macos-touristd-config

### ISSUE THREAD

**Issue by apizz** [ProfileCreator/macos-touristd-config#3]
@wegotoeleven Have been getting repeated run failures the last several days:

https://github.com/ProfileCreator/macos-touristd-config/actions

**Comment by wegotoeleven** [comment]
Looks like an SSL issue on the runner. @apizz Can you add me as a user to this repo directly, or would you rather I make forks and PRs?

**Comment by apizz** [comment]
@wegotoeleven just added you as a maintainer

**Comment by wegotoeleven** [comment]
I'm not _entirely_ sure why SSL was failing, but I've added a `-k` switch to `curl`, which has fixed the issue!

**Comment by apizz** [comment]
Will see if we get an error this evening when it runs. thanks!

**Comment by apizz** [comment]
Oh I see you ran manually successfully.  Huzzah! :)
